### ISSUE TITLE
which solution to choose?

### ISSUE THREAD

**Issue by xilinniao123** [ku21fan/CLL-STR#1]
thanks for sharing! when meet low-resource language , two solution： one is use Synthetic Data；other is cross-lingual learning (CLL) which mentioned in
 your paper？ how to choose between the 2 solution？ can you give some suggestions? thanks

**Comment by ku21fan** [comment]
Hi, 

Thank you for your interest in our work!

> how to choose between the 2 solution？

It is up to your situation, and I think you can use both simultaneously: synthetic data and cross-lingual learning. 
Especially when you don't have synthetic data for low-resource language, you can use synthetic data for high-resource language such as English and conduct cross-lingual learning for better performance!

Regarding our paper, we submitted it to arXiv this morning, and it will take one day to be released. 
According to arXiv, it will be released on Tue, 19 Dec 2023, 01:00:00 GMT.

Best regards,
